package com.example.sellbuy.model.entity.enums;

public enum LocationEnum {
    SOFIA, SOFIA_GRAD, PERNIK, KYUSTENDIL, BLAGOEVGRAD, PAZARDJIK,PLOVDIV, LOVECH, VRATSA, MONTANA,
    VIDIN, PLEVEN, GABROVO, STARA_ZAGORA, SMOLYAN, KARDJALI, HASKOVO, YAMBOL, SLIVEN, BURGAS, SHUMEN,
    TARGOVISHTE, RUSE, RAZGRAD, SILISTRA, VELIKO_TYRNOVO, DOBRICH, VARNA;
}
